### ISSUE TITLE
ImportError: DLL load failed while importing pyhtml2md

### ISSUE THREAD

**Issue by obskyr** [tim-gromeyer/html2md#133]
**Describe the bug**
After installing `pyhtml2md`, I cannot import it due to an `ImportError: DLL load failed while importing pyhtml2md`.

**To Reproduce**
1. Run `pip3 install pyhtml2md`
2. Attempt to `import pyhtml2md`. The following error occurs:
   
   ```
   >>> import pyhtml2md
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
   ImportError: DLL load failed while importing pyhtml2md: The specified module could not be found.
   ```

**Expected behavior**
For the module to load.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19045 (x64)
 - Python version: 3.12.3

**Additional context**
I presume this has to be an environment issue, somehow. I haven't written a Python module that uses a DLL myself&nbsp;– what could the issue be?

**Comment by tim-gromeyer** [comment]
I really have no glue at all. I'll update the dependencies used for python (pybind, cibuildwheel) and create a release. Hopefully that fixes it

**Comment by tim-gromeyer** [comment]
I have no glue how to fix this

**Comment by tim-gromeyer** [comment]
I updated the code, to upload pre-build python wheels to pypi. Can you update to v1.6.6 and test again?

**Comment by DWesl** [comment]
In case that doesn't work, some suggestions for debugging:

`python -dvvv -c 'import pyhtml2md'` would include what file it's trying to import, among many other things: you might want to run the output through `grep -C3 html` before looking at it to reduce the output to a dozen lines or so.  This would help rule out simple problems like forgetting to package the DLL in the wheel or packaging the 3.9 DLL in the 3.12 wheel

One simple check would be whether you have execute permissions on the DLL python's trying to open: I don't remember if it's `icacls ${dll}` or `getfacl ${dll}` on Windows, nor whether `dir ${dll}` provides permissions on Windows.  It might be simplest to check with [`os.stat`](https://docs.python.org/3/library/os.html#os.stat) (`os.chmod(dll_name, os.stat(dll_name).st_mode | stat.S_IXUSR)` should set the permissions properly).

Next up on the would be checking whether the DLL it's trying to open can load its dependencies, which [the build file](https://github.com/tim-gromeyer/html2md/blob/598c66d4e8349539a55d9dcf317801f938ba051f/CMakeLists.txt#L51) suggests should be just `python3.12.dll`, which is probably next to `python3.12.exe`.  If that is the problem, calling [`os.add_dll_directory`](https://docs.python.org/3/library/os.html#os.add_dll_directory) with the directory or directories containing those DLLs before attempting the import should work.

**Comment by obskyr** [comment]
Adding my entire `path` using `os.add_dll_directory`, as @DWesl suggested, did the trick:

```python
import os

for path in os.getenv('PATH').strip(os.pathsep).split(os.pathsep):
    try:
        os.add_dll_directory(path)
    except OSError:
        pass

import pyhtml2md
```

This would suggest that this is an issue for everyone trying to use this library on Windows. (Still don’t know which DLL it is…!)
